### ISSUE TITLE
Game crash by using "Chisel and bits" or looking for recipes with smithing table

### ISSUE THREAD

**Issue by SikiciBebek** [Robocraft999/CreateGoggles#22] opened 2023-09-03 14:51 UTC
Everytime a player looking up for a recipe inside a smithing table the game crashes. Same thing happens if someone is building with chisel and bits.

https://mclo.gs/1AZf7z0 -> latest log
https://mclo.gs/cwfCdhX -> crasht report

Modpack: KOTD (curseforge)
Mod version = newest one

**Comment by Robocraft999** [comment] 2023-09-03 15:10
I see. This is the same error as #18 . The Problem is Forbidden and arcanus. It will be fixed in the next update

**Comment by SikiciBebek** [comment] 2023-09-03 15:14
ty! ^^

**Closed as completed** 2023-09-03 15:14 UTC
