### ISSUE TITLE
Create Goggles failed to start on Fabric Server

### ISSUE THREAD

**Issue by Progeilo425** [Robocraft999/CreateGoggles#6] opened 2023-04-30 14:03 UTC
Version: 
create-fabric-0.5.0.i-1003+1.19.2
creategoggles-0.5.4.1-[FABRIC]
architectury-6.5.77-fabric
(Also tested on Server with create-fabric-0.5.0.i-991+1.19.2)

When loading process is done this error message was been printed in Console.

Console Output: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'creategoggles'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
	at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
	at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
	at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more

**Comment by TimDev9492** [comment] 2023-05-04 11:31
Same error here, using fabric 1.19.2 server with Create Goggles 0.5.4.1, this is the output in a more readable format:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'creategoggles'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
        at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
        at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
        at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
        ... 8 more
```

**Comment by Avchong** [comment] 2023-05-04 21:54
Same issue on my Server
[crash-2023-04-30_01.27.00-server.txt](https://github.com/Robocraft999/CreateGoggles/files/11401869/crash-2023-04-30_01.27.00-server.txt)

here's the whole crash report

**Comment by PolarbaerHD** [comment] 2023-05-06 05:28
###Got the same problem.###
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'creategoggles'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at com.robocraft999.creategoggles.CreateGoggles.init(CreateGoggles.java:32) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:9) ~[creategoggles-0.5.4.1-%5BFABRIC%5D.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
... 8 more`

**Comment by Robocraft999** [comment] 2023-05-09 18:34
should be fixed now

**Closed as completed by Robocraft999** 2023-05-09 18:34 UTC
